version: '3.8'

services:
  postgres:
    image: postgres
    container_name: projeto-biblioteca
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 987
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    restart: unless-stopped